name: duengine
version: 0.0.1
description: DuEngine is a 2D Game Engine build uppon the library GorgonDart.
environment:
  sdk: '>=1.5.2'
dependencies:
  async: '>=1.0.0 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
  gorgon: '>=0.14.0 <0.15.0'
dev_dependencies:
  http_server: any
  mockito: '>=0.8.1 <0.9.0'
  unittest: '>=0.11.0+2 <0.12.0'
